nav = document.getElementById("navig");

data = ''
+ '<div class="col apart-1-10 link abc-d ac-g-0">'
+ '	<a href="/Masters" class="atext-15 atext-center atext-ind-s">Друзья</a>'
+ '</div>'
+ '<div class="col apart-1-10 link abc-d ac-g">'
+ '	<a href="/Street" class="atext-15 atext-center atext-ind-s">Блоги</a>'
+ '</div>'
+ '<div class="col apart-1-10 link abc-d ac-g-1">'
+ '	<a href="/News" class="atext-15 atext-center atext-ind-s">Новости</a>'
+ '</div>'
+ '<div class="col apart-1-10 link abc-d ac-g-2">'
+ '	<a href="/Chr" class="atext-15 atext-center atext-ind-s">Статьи</a>'
+ '</div>'
+ '<div class="link abc-d ac-l apart-2-10">'
+ '	<a href="/" class="atext-40 atext-center atext-ind-s">Домой</a>'
+ '</div>'
+ '<div class="col apart-1-10 link abc-d ac-b-2">'
+ '	<a href="/Vega" class="atext-15 atext-center atext-ind-s">Веган</a>'
+ '</div>'
+ '<div class="col apart-1-10 link abc-d ac-b">'
+ '	<a href="/Buddy" class="atext-15 atext-center atext-ind-s">Ужасы Бадди</a>'
+ '</div>'
+ '<div class="col apart-1-10 link abc-d ac-b-0">'
+ '	<a href="/StoneDust" class="atext-15 atext-center atext-ind-s">Пыль Камней</a>'
+ '</div>'
+ '<div class="col apart-1-10 link abc-d ac-b-1">'
+ '	<a href="/JoT" class="atext-15 atext-center atext-ind-s">Журнал Приручения</a>'
+ '</div>';

nav.innerHTML = data